[build]
publish = "_site"
command = "npm run prod"

[dev]
command = "npm run dev"

[functions]
directory = "functions"
node_bundler = "esbuild"
external_node_modules = [
  "prismjs",
  "@11ty/eleventy",
  "@11ty/dependency-tree",
  "pug-filters"
]

[[redirects]]
from = "/getcode/"
to = "/.netlify/functions/getcode"
status = 200
force = true
_generated_by_eleventy_serverless = "getcode"
