[build]
    publish = "_site"
    command = "npm run prod"
    functions = "functions"
[build.processing]
    skip_processing = false
[build.processing.css]
    bundle = false
    minify = true
[build.processing.js]
    bundle = false
    minify = true
[build.processing.html]
    pretty_urls = false
[build.processing.images]
    compress = true
[dev]
    command = "npm run dev"
[functions]
  directory = "functions"
  node_bundler = "esbuild"
[[redirects]]
  from = "/getsource/"
  to = "/.netlify/functions/getsource"
  status = 200